### ISSUE TITLE
Issue with running the Yowllr chat app

### ISSUE THREAD

**Issue by kmuthukrishnan** [jlooper/Yowwlr#3]
Hi @jlooper ,

I am trying to run theYowwlr (twoitter for cats :)) app. But, I am running into problems once I have done the npm install and platform add android. 

tns run android is giving me the following error: 

```
app/app.module.ts(1,10): error TS2305: Module '"/home/krithika/SVNcode/nativescript/Yowwlr-master/node_modules/nativescript-angular/platform"' has no exported member 'NativeScriptModule'.

app/home/home.module.ts(1,10): error TS2305: Module '"/home/krithika/SVNcode/nativescript/Yowwlr-master/node_modules/nativescript-angular/platform"' has no exported member 'NativeScriptModule'.

app/login/login.module.ts(1,10): error TS2305: Module '"/home/krithika/SVNcode/nativescript/Yowwlr-master/node_modules/nativescript-angular/platform"' has no exported member 'NativeScriptModule'.

node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts(15,48): error TS2304: Cannot find name 'Iterable'.

Unable to apply changes on device: cdb18c57. Error is: TypeScript compiler failed with exit code 1.
```
Can you please help me figure out what I can do? Iam trying to implement a similar functionality for customer support on the app and having yours as reference would be helpful. 

Thanks!
@kmuthukrishnan

**Comment by jlooper** [comment]
hi, looks like this repo needs an update to the latest NativeScript. Let me fix it and get back to you. Thanks!

**Comment by jlooper** [comment]
This should be working now.

**Comment by kmuthukrishnan** [comment]
Thanks, will check.
